### ISSUE TITLE
DNA Sign Text Z Fighting

### ISSUE THREAD

**Issue by drewc5131** [darktohka/libtoontown#1]
Due to a change in the text rendering since toontown, sign text doesnt work properly.
![image](https://user-images.githubusercontent.com/31282527/93005892-d4bc6b80-f523-11ea-8cf7-a9357ad512fe.png)
![image](https://user-images.githubusercontent.com/31282527/93005894-d71ec580-f523-11ea-97f7-fbb211d9880c.png)

**Comment by darktohka** [comment]
Resolved in 3d959a617beeb7c1bade4f43c88f97ff5453f076.
