### ISSUE TITLE
When using libtoontown instead of libpandadna certain doors won't work.

### ISSUE THREAD

**Issue by DarthMDev** [darktohka/libtoontown#10]
When trying to enter doors such as the ones inside of playground and street buildings, your estate door, and cog HQ doors they simply won't let you enter. 
They don't crash you, it's just like won't register the input it seems that you are entering a door.
Other doors work fine though.

**Comment by ooowoothevirtualhowler** [comment]
Super late answer but this isn't really an issue with DNA. It's caused by the frame rate being too high so you pass straight through the collision since some doors have really small collisions.

**Comment by DarthMDev** [comment]
Yeah I fixed the issue on my source by moving the door triggers in the source code
